/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.18 laravel.gltf --transform 
Files: laravel.gltf [110.46KB] > C:\Users\admin\AppData\Local\Temp\Rar$EXa3836.31788.rartemp\Downloads\dyud\01- Laravel.Logo\laravel-transformed.glb [39.57KB] (64%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'
import laravel from '../assets/objet3d/laravel-transformed.glb'

export function Laravel3d(props) {
  const { nodes, materials } = useGLTF(laravel)
  console.log(materials);
  return (
    <group {...props} dispose={null}>
         <ambientLight intensity={1}/>
         <directionalLight intensity={7} position={[0,0,100]}/>
         <directionalLight intensity={7} position={[0,0,-100]}/>
         <directionalLight intensity={3} position={[100,0,0]}/>
         <directionalLight intensity={3} position={[-100,0,0]}/>
         <directionalLight intensity={3} position={[0,100,0]}/>
         <directionalLight intensity={3} position={[0,-100,0]}/>
      <mesh geometry={nodes.Curve_SVGMat003_0.geometry} shine={10} material={materials['SVGMat.003']} position={[0.226, 0, -0.031]} rotation={[-0.011, 0, 0]} scale={[120, 120, 120]}/>
    </group>
  )
}

useGLTF.preload(laravel)
