/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.18 react_native.gltf --transform 
Files: react_native.gltf [84.85MB] > C:\Users\admin\AppData\Local\Temp\Rar$EXa3836.31788.rartemp\Downloads\dyud\03- React.Icon\react_native-transformed.glb [35.29MB] (58%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'
import react from '../assets/objet3d/react_native-transformed.glb'
export function ReactNative3d(props) {
  const { nodes, materials } = useGLTF(react);
  return (
    <group {...props} dispose={null}>
         <ambientLight intensity={1}/>
         <directionalLight intensity={10} position={[0,0,100]}/>
      <mesh geometry={nodes.Curve_Material_0.geometry} material={materials.Material} position={[0, 0, -0.6]} rotation={[0.017, 0.05, -1.55]} scale={1.4147*2} />
      <mesh geometry={nodes.Cylinder_Material003_0.geometry} material={materials['Material.003']} position={[0, 0, -0.69]} rotation={[0.008, 0.034, -1.547]} scale={[1.1431*2, 1.1431*2, 0.1133*2]} />
    </group>
  )
}

useGLTF.preload(react)
